[package]
name = "elpian"
version = "0.1.1"
edition = "2024"

[dependencies]
serde_json = "1.0.145"
wasm-bindgen = "0.2.105"
once_cell = "1.18"
bevy = "0.15"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
notify = "6.1"
jsonschema = "0.18"

[lib]
crate-type = ["cdylib", "rlib"]
